CREATE TABLE PF_EMAIL  (
	EMAIL_ID BIGINT  NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CREATED_AT DATETIME NOT NULL,
	TO_EMAIL VARCHAR(250) ,
	FROM_EMAIL VARCHAR(250) ,
	SUBJECT_EMAIL VARCHAR(250) ,
	BODY_EMAIL TEXT NULL ,
	SENT_TIME DATETIME NULL,
	IS_VALID BOOLEAN NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;